embed_assets: on

javascripts:
  app:
    - public/javascripts/excanvas/*.js
    - public/javascripts/vendor/jquery-1.6.2.js
    - public/javascripts/flot/*
    - public/javascripts/app/*.js
  shammes:
    - public/javascripts/shammes.js

stylesheets:
  common:
    - public/stylesheets/grid.css
    - public/stylesheets/text.css
    - public/stylesheets/screen.css

