# mongodb://<user>:<password>@staff.mongohq.com:10039/fuelbroker
mongohq: &mongohq
  host: flame.mongohq.com
  port: 27053
  username: vicente.reig
  password: kripton
  database: shammes

local: &local
  host: localhost
  database: shammes_dev

development: *mongohq

test:
  host: localhost
  database: shammes_test

# set these environment variables on your prod server
production:
  host: flame.mongohq.com
  port: 27053
  username: vicente.reig
  password: kripton
  database: shammes